name: AI Intel Daily

on:
  schedule:
    - cron: "0 8 * * *" # daily at 08:00 UTC (≈ 09:00 BST)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ingest
        run: |
          python -m ai_intel_pipeline ingest --limit 12
      - name: Digest
        run: |
          python -m ai_intel_pipeline digest --week current
      - name: Build embeddings index
        run: |
          python -m ai_intel_pipeline index-model
      - name: Generate status report
        run: |
          python -m ai_intel_pipeline report
      - name: Export RAG JSONL
        run: |
          python -m ai_intel_pipeline export
      - name: Upload digest artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly-digest
          path: vault/digests/weekly/
      - name: Upload vault snapshot
        uses: actions/upload-artifact@v4
        with:
          name: vault-snapshot
          path: vault/
      - name: Upload model index
        uses: actions/upload-artifact@v4
        with:
          name: model-index
          path: vault/model/
      - name: Upload status report
        uses: actions/upload-artifact@v4
        with:
          name: status-report
          path: vault/status/
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
