name: AI Intel Daily

on:
  schedule:
    - cron: "0 8 * * *" # daily at 08:00 UTC (≈ 09:00 BST)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Debug secrets presence (no values)
        run: |
          if [ -n "${OPENAI_API_KEY}" ]; then echo "OPENAI=SET"; else echo "OPENAI=NOTSET"; fi
          if [ -n "${ANTHROPIC_API_KEY}" ]; then echo "ANTHROPIC=SET"; else echo "ANTHROPIC=NOTSET"; fi
      - name: Ingest
        run: |
          python -m ai_intel_pipeline ingest --limit 12
      - name: Digest
        run: |
          python -m ai_intel_pipeline digest --week current
      - name: Export RAG JSONL
        run: |
          python -m ai_intel_pipeline export
      - name: Upload digest artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly-digest
          path: vault/digests/weekly/
      - name: Upload vault snapshot
        uses: actions/upload-artifact@v4
        with:
          name: vault-snapshot
          path: vault/
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
