name: AI Intel Daily

on:
  schedule:
    - cron: "0 8 * * *" # daily at 08:00 UTC (≈ 09:00 BST)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ingest
        run: |
          python -m ai_intel_pipeline ingest --limit 12
      - name: Digest
        run: |
          python -m ai_intel_pipeline digest --week current
      - name: Build embeddings index
        run: |
          python -m ai_intel_pipeline index-model
      
      - name: Copy UI files to status
        shell: bash
        run: |
          mkdir -p vault/ai-intel/status
          cp -r ui/* vault/ai-intel/status/
          echo '{' > vault/ai-intel/status/build.json
          echo '  "sha": "'${GITHUB_SHA}'",' >> vault/ai-intel/status/build.json
          echo '  "run_id": "'${GITHUB_RUN_ID}'",' >> vault/ai-intel/status/build.json
          echo '  "ts": "'$(date -u +%FT%TZ)'"' >> vault/ai-intel/status/build.json
          echo '}' >> vault/ai-intel/status/build.json
      - name: Export RAG JSONL
        run: |
          python -m ai_intel_pipeline export
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build web UI
        working-directory: web
        run: |
          npm ci || npm i
          npm run build
      - name: Copy web UI to status
        shell: bash
        run: |
          mkdir -p vault/ai-intel/status
          cp -r web/dist/* vault/ai-intel/status/
          echo '{' > vault/ai-intel/status/build.json
          echo '  "sha": "'${GITHUB_SHA}'",' >> vault/ai-intel/status/build.json
          echo '  "run_id": "'${GITHUB_RUN_ID}'",' >> vault/ai-intel/status/build.json
          echo '  "ts": "'$(date -u +%FT%TZ)'"' >> vault/ai-intel/status/build.json
          echo '}' >> vault/ai-intel/status/build.json
      - name: Upload digest artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly-digest
          path: vault/digests/weekly/
      - name: Upload vault snapshot
        uses: actions/upload-artifact@v4
        with:
          name: vault-snapshot
          path: vault/
      - name: Upload model index
        uses: actions/upload-artifact@v4
        with:
          name: model-index
          path: vault/model/
      - name: Upload status report
        uses: actions/upload-artifact@v4
        with:
          name: status-report
          path: vault/ai-intel/status/
      - name: Upload Pages artifact (dashboard)
        uses: actions/upload-pages-artifact@v3
        with:
          path: vault/ai-intel/status
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
      - name: Read email body
        id: read_email
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const html = fs.readFileSync('vault/ai-intel/status/email.html', 'utf8');
            core.setOutput('html', html);
      - name: Check SMTP secrets
        id: smtp
        shell: bash
        run: |
          ok=true
          [ -n "${{ secrets.SMTP_SERVER }}" ] || ok=false
          [ -n "${{ secrets.SMTP_USERNAME }}" ] || ok=false
          [ -n "${{ secrets.SMTP_PASSWORD }}" ] || ok=false
          [ -n "${{ secrets.TO_EMAIL }}" ] || ok=false
          [ -n "${{ secrets.FROM_EMAIL }}" ] || ok=false
          echo "enabled=${ok}" >> "$GITHUB_OUTPUT"
      - name: Send daily email
        if: steps.smtp.outputs.enabled == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: AI Intel Daily Report
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          content_type: text/html
          body: ${{ steps.read_email.outputs.html }}
          attachments: |
            vault/ai-intel/status/report.md
            vault/digests/weekly/*.md
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
