name: AI Intel Feedback

on:
  workflow_dispatch:
    inputs:
      item_id:
        description: "Item ID"
        required: true
        type: string
      decision:
        description: "Decision (accept|reject)"
        required: true
        type: choice
        options:
          - accept
          - reject

jobs:
  update-weights:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Apply feedback
        env:
          ITEM_ID: ${{ inputs.item_id }}
          DECISION: ${{ inputs.decision }}
        run: |
          python -m ai_intel_pipeline feedback --item-id "$ITEM_ID" --decision "$DECISION"
      - name: Commit and push policy update
        run: |
          git config user.name ai-intel-bot
          git config user.email bot@example.com
          git add config/policy/weights.json
          git commit -m "chore(policy): feedback ${{ inputs.decision }} for ${{ inputs.item_id }}"
          git push

