name: AI Intel Ingest URL

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Source URL (YouTube or GitHub)"
        required: true
        type: string

jobs:
  ingest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ingest single URL
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          python -m ai_intel_pipeline ingest-url --url "${{ inputs.url }}"
      - name: Upload vault snapshot
        uses: actions/upload-artifact@v4
        with:
          name: vault-after-manual-ingest
          path: vault/

