name: AI Intel Weekly Digest

on:
  schedule:
    - cron: "0 8 * * 5" # Fridays 08:00 UTC
  workflow_dispatch: {}

jobs:
  weekly:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip
          pip install -r ai-intel-pipeline/requirements.txt
      - name: Compose weekly digest
        run: |
          python -m ai_intel_pipeline digest --week current
        working-directory: ai-intel-pipeline
      - name: Upload weekly digest
        uses: actions/upload-artifact@v4
        with:
          name: weekly-digest
          path: ai-intel-pipeline/vault/digests/weekly/
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

